ODIM-Project/PluginCiscoACI

- capdata/data.go
- caphandler/ports.go
- capmodel/aciPort.go
- caputilities/aciClient.go
- go.mod
- go.sum
- main.go
As part of this pr  #6  task `Querying port information`  is  completed
> ACI 6:Retreving the switch ports  information  during plugin start up

- capdata/data.go
- caphandler/fabrics.go
- caphandler/ports.go
- caphandler/switches.go
- capmodel/aciEntityHelath.go
- capmodel/aciPort.go
- capmodel/fabricHelath.go
- capmodel/switchChassis.go
- capmodel/switchHelath.go
- caputilities/aciClient.go
- main.go
As part of this additional attributes in  added in getting of Fabric, Switch and Port  for issue #6
> ACI 6:Updating the additional attributes in get of Fabric, Switch and Port

- caphandler/managers.go
- go.mod
- go.sum
As part of this PR `Update manager response managed switches data` in #6  is completed
> Aci 6:Adding switch info in the Managers response 

- caphandler/fabrics.go
- caphandler/managers.go
- caphandler/ports.go
- caphandler/switches.go
- caputilities/aciClient.go
- go.mod
- go.sum
- main.go
As part of this  additional attributes are added in Port response  and Not found case error response is added for #6
> Aci 6: Adding additional attributes in Port response 

- capdata/data.go
- caphandler/addresspools.go
- main.go
As part of this pr ` Implement post and get  handlers for AddressPool operation` is completed for #15
> Aci 15:Adding Post,Get Collection and Get on address pool

- capdata/data.go
- caphandler/zones.go
- capmodel/fabricHelath.go
- caputilities/aciClient.go
- go.mod
- go.sum
- main.go
This PR contains the following implementations
- Create Default Zone handler
- List Zones 
- Retrieve individual Zone
- Delete individual Zone
> Default Zone Creation, Retrieval and Deletion

- caphandler/zones.go
This PR contains the following changes:
Response FIX on DataStore
Check existing AP's for conflict response
Create VRF
Check existing VRF's for conflict response
> Odim 4380: Create VRF with conflict checks in ZoneOfZones

- caphandler/zones.go
This PR contains the following:
- Delete Application profile in ACI with delete of ZoneOfZones
- Delete VRF in ACI with delete of ZoneOfZones
> Odim 4380: Delete Application profile and VRF

- caphandler/addresspools.go
- caphandler/zones.go
- go.mod
- go.sum
> Aci 15:Adding logic to delete ZoneOfEndpoints

- install/Docker/dockerfiles/Dockerfile.aciplugin
- install/Kubernetes/helmcharts/aciplugin-config.yaml
- install/Kubernetes/helmcharts/aciplugin/templates/configmaps.yaml
- install/Kubernetes/helmcharts/aciplugin/values.yaml
Fixed dockerimage build & deployment of configmap
resolves #39
> Dockerimage build fix

- Makefile
- build/Dockerfile.builddep
- caphandler/zones.go
- caputilities/aciClient.go
> Aci 36:Adding contract creation in ZoneofZone creation 

- install/Kubernetes/helmcharts/aciplugin-config.yaml
- install/Kubernetes/helmcharts/aciplugin/templates/configmaps.yaml
- install/Kubernetes/helmcharts/aciplugin/values.yaml
> Helm manifest file update- configmap.yaml

- caphandler/zones.go
- main.go
> Aci 54:Adding support for patch on zone of Endpoints 

- caphandler/managers_test.go
- capmodel/aciPort.go
- capmodel/aciPort_test.go
- capmodel/addresspools.go
- capmodel/common.go
- capmodel/common_test.go
- capmodel/endpoints.go
- capmodel/fabric.go
- capmodel/fabric_test.go
- capmodel/switchChassis.go
- capmodel/zone.go
- capmodel/zone_test.go
- db/constants.go
- db/mockOperations.go
> issue-17 : clean up redundant code

- caphandler/endpoints.go
> aci64:Removing association of Endpoints from zoneOfEndpoints during deletion of Endpoints

- caphandler/endpoints.go
- caphandler/pluginStatus.go
- capmodel/common.go
- main.go
> Aci 65:Publishing the resource Added event after  the initial plugin status request 

- caphandler/zones.go
> aci-70:Updating parentzone variable initialization in delete zoneofzone

- caphandler/ports.go
- capmodel/aciPort.go
> issue-71 : update port data in DB for patch on ports req

- caphandler/zones.go
Updating the default zone link after the APIC communication is completed
LFN Jira issue link:https://jira.lfnetworking.org/browse/ODIM-2
> odim-2:Updating the default zone link after the apic communication completed

- caphandler/zones.go
This pr contains the changes to   support deletion multiple zoneofzone
LFN Jira issue link:https://jira.lfnetworking.org/browse/ODIM-3
> Odim 3:Updating the link updating to  support deletion multiple zoneofzone

- README.md
Merging ACI Plugin Readme content from my feature branch to the Upstream Dev branch
> ACI Plugin Readme - Phase 3

- caphandler/addresspools.go
- caphandler/zones.go
Adding changes related to the untagged and Multivlan
> aci 36:Adding changes related to the untagged and multivlan

- README.md
Update CiscoACI docker image version and add a missed step in deployment instrcutions in the ACI readme
> Merge to Dev- Update CiscoACI docker image version and add a missed step in deployment instructions

- README.md
Merge to Release branch - Updating ACI readme with relevant feedback items given for the plugin sections in the Getting Started readme
> Merge to Release branch - Updating relevant feedback items given for the plugin sections in the Getting Started readme

- README.md
Merge to dev: 
- Updated information on passing the encrypted password in odimPassword parameter while deploying ACI plugin
- Update the odimPassword parameter in the plugin configuration parameters section
- Replaced apicHost with a public IP.
> Merge to Dev - ACI plugin deployment updates 

- README.md
Merge to dev 
- Replace IPs with valid public IPs
- Replace colons with period symbol
- Remove common response headers
> Merge to dev - Replace IPs with valid public IPs, replace colons with period symbol and remove common response headers

- README.md
team feedback on aci readme to update docker version of aci plugin from 3.0 to 3.1 + styleguide fixes
> Merge to dev - team feedback on aci readme

- README.md
Update plugin deployment instructions with steeps 3.3 and 3.4
> Merge to dev - Update deployment instructions 

- .github/workflows/build_unittest.yml
- build/Dockerfile.builddep
- go.mod
- install/Docker/dockerfiles/Dockerfile.aciplugin
- install/Docker/dockerfiles/scripts/add-hosts/go.mod
Upgrade golang version to 1.19.5
> Upgrade golang version to 1.19.5

- build_images.sh
- install/Kubernetes/helmcharts/aciplugin/Chart.yaml
- install/Kubernetes/helmcharts/aciplugin/values.yaml
Upgrade the image versions in plugin
> Upgrade the image versions in plugin

- README.md
Updated aci image version to 3.3 as per team feedback
> updated aci image version 
